### ISSUE TITLE
match users logged in via Fedora OpenID to Fedora ACLs from storage

### ISSUE THREAD

**Issue by mozeq** [abrt/faf#100]
Opened '20121112T10:23:55' by mtoman as https://fedorahosted.org/abrt/ticket/861

Basic implementation, eg. Fedora user might have pre-selected components that he maintains.

**Comment by mbrysa** [comment]
Closed via https://github.com/abrt/faf/commit/53b8265c1578978838a43dc736c7a38c869699fb
