### ISSUE TITLE
Login page times out

### ISSUE THREAD

**Issue by ArnaudKleinveld** [abrt/faf#1001]
java-11-openjdk quit unexpectedly > Click report

    --- Running report_uReport ---
    Server responded with an error: 'uReport data is invalid.'
    ('report_uReport' exited with 1)

Not sure where to go from there following the instructions because of the many workflows. Then I notice one "Process the Java exception using the Fedora infrastructure" and I assume it's this one. My email address is in there so I go to the website to check if it is a valid login as well. 

Visiting [retrace.fedoraproject.org/faf/login](https://retrace.fedoraproject.org/faf/login/) time out

This process needs to be improved for reporting to return valuable data I would think. It's unclear which workflow to review when the abort report fails and there is something wrong with the login on the above mentioned website.

**Comment by mgrabovsky** [comment]
Thank you for your report, Arnaud. I've taken the liberty of reformatting your post a bit to make it more readable – the markup was slightly broken, but I've kept your words.

There seem to be three bugs here actually: one is the login page timing out, another is the suboptimal user experience around failures and the last one is the “uReport data is invalid” error.

I'm keeping this ticket dedicated to the first issue. We're tracking the user experience problems elsewhere.

**Comment by ArnaudKleinveld** [comment]
Thank you Matěj, good job on isolating the three issues. Do you have a reference for the issue of uReport data being invalid? I'd really like to report an issue with java-11-openjdk-headless using the abort problem reporting facility.

**Comment by mgrabovsky** [comment]
@ArnaudKleinveld Is the timeout on the login page still a problem for you?

**Comment by ArnaudKleinveld** [comment]
No more timeout.Thanks
