### ISSUE TITLE
Kaffeine crash with Wayland

### ISSUE THREAD

**Issue by felixltx** [abrt/faf#1007]
Since Wayland, kaffeine crash after few seconds. It works perfectly with X11.

**Comment by felixltx** [comment]
https://retrace.fedoraproject.org/faf/reports/bthash/dcca74bb1ae89033faada04795c13ae5b3bb3edb

**Comment by mgrabovsky** [comment]
This is the bug tracker for ARBT Analytics only. To report a bug in Kaffeine, plese use the [KDE bug tracker](https://bugs.kde.org/enter_bug.cgi?format=guided&product=kaffeine).
