### ISSUE TITLE
get the live instance under fedora infrastructure supervision

### ISSUE THREAD

**Issue by mozeq** [abrt/faf#135]
- write SOP document describing the running services, configuration, common problems with solutions
- make sure it's added here: http://status.fedoraproject.org/

**Comment by sorki** [comment]
Ansible recipes now production ready - https://github.com/abrt/abrt-ansible

Discussion with fedora infra team ongoing.

**Comment by xsuchy** [comment]
Fedora ansible roles are here:
https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/abrt

SOP is on the way.

**Comment by xsuchy** [comment]
SOP is in ./docs/sysadmin-guide/sops/retrace.rst
ABRT is present on status page.
