### ISSUE TITLE
add an option to manually create a bugzilla ticket from problem

### ISSUE THREAD

**Issue by mozeq** [abrt/faf#149]
faf should provide a way to create a bz ticket(or ticket in some tracking system) when maintainer finds a report which is valid and needs fixing and decides to create a bugzilla for it.

**Comment by jfilak** [comment]
@AdamWill I have a good news for you! @mbrysa upgraded https://retrace.fedoraproject.org/faf . Can you please check this functionality out and share with us your feedback?

Login -> find a report without Bugzilla -> open the report's page -> Associate bug
