### ISSUE TITLE
Add possibility to hide reports containing proprietary modules

### ISSUE THREAD

**Issue by sorki** [abrt/faf#184]
It should be possible to hide problems matching knowledge base entries.

**Comment by mbrysa** [comment]
Is this closed via https://github.com/abrt/faf/commit/e8b2a7b4f864e96ccdc95abf1decbc2b15de1e2d by being able to filter out problems with the `P` flag?

**Comment by sorki** [comment]
Probably yes but I'm not sure what knowledge base entries we use - I think we can close this as the only proprietary non-kernel module that comes to my mind is flash that's being phased out of internetz.
