### ISSUE TITLE
Don't file bz bugs for user code

### ISSUE THREAD

**Issue by opoplawski** [abrt/faf#195]
https://bugzilla.redhat.com/show_bug.cgi?id=955077 

This crash is occurring in user created code:

/ourwork/projects/dudi/vec_m_matrix/verilator/Vlarge_mat_vec_mult.oct

These kinds of crashes need to be excluded from reporting.

**Comment by xsuchy** [comment]
I believe, that nowadays we do not include reports from unpackages SW - it is config drivend and default is to not report it.
