### ISSUE TITLE
add an option to watch component

### ISSUE THREAD

**Issue by mozeq** [abrt/faf#215]
Faf should provide a way to watch component stability. The idea I have is like this: If someone (maintainer, developer, manager, etc..) wants to get notification when the number of reports against his component crosses some threshold he would log in to faf and click "watch component". Later we can add some sophisticated filters (like conditions, custom thresholds, etc..) but I think for the first version FAF could just send notification whenever the component gets to the top 20 (??) hot problems.

**Comment by jfilak** [comment]
On the Fedora instance, we can preconfigure all accounts by synchronization with Bug Watchers lists from *Fedora Package Database*.

**Comment by jfilak** [comment]
Currently, Fedora package Committers and Fedora package Watchers are notified if the crash occurrence counter reaches 10, 100, 1000, 10000 reports.

https://github.com/abrt/faf/wiki/Maintainer-notifications#fedmsg

**Comment by xsuchy** [comment]
Closing then.
