### ISSUE TITLE
kernel report filtering/handling

### ISSUE THREAD

**Issue by jwboyer** [abrt/faf#331]
The reports filed in retrace for the kernel can be very useful, but at the moment there is no way to filter out reports that are uninteresting or unhelpful.  Looking at the top 10 problems reported for the kernel component, we can see that there are a number of duplicate issues, a large number of them tainted, and some of those tainted with the P or O taints set.

It would be nice for logged in users to deal with this in a number of ways.  For instance, in addition to filtering on Release and Architecture, it would be nice to be able to filter:

- Whether taint is set, and which taint it is.  E.g. Get all of the problem reports for the kernel that do not have the P or O taints set (or D, I, etc).
- By NEVR.  E.g. Get all of the problem reports for kernels between 3.16.0 and 3.17.3, but not older.  There are often times reports from older kernels that are high in count number but that realistically we cannot fix because we've rebased well beyond that version.

Additionally, it would be nice to be able to manually mark reports as duplicates, or merge them somehow.  If you look at the top 5 problems for the kernel, 4 of them are actually all the same problem (478234, 486033, 499589, 471284).  Being able to merge those into a single problem would give a more accurate count for that specific issue while reducing the actual number of problems.  I realize this is somewhat more of a duplication detection issue, but being able to do this manually would still be helpful.

I may have more items that I think of later, but I believe this captures most of the issues that are hindering us a bit when we look at retrace reports for the kernel.

**Comment by sorki** [comment]
All of this is implemented and now deployed on https://retrace.fedoraproject.org/faf/

Example query for filtering kernel versions since 3.20:
https://retrace.fedoraproject.org/faf/problems/?component_names=kernel&daterange=2014-02-24%3A2015-03-10&since_version=3.20
