### ISSUE TITLE
Generate bugzilla bugs with abrt_duphash

### ISSUE THREAD

**Issue by jfilak** [abrt/faf#374]
#### C/C++:

`sr_thread_get_duphash(crash_thread, 3, component, SR_DUPHASH_NORMAL);`
#### Kernel oops:

`sr_thread_get_duphash(crash_thread, 6, NULL, SR_DUPHASH_NONORMALIZE|SR_DUPHASH_KOOPS_COMPAT);`
#### Python:

SHA1 of the 1st line of backtrace (str(Exception)) (D`oh, we don't have it, we should DUPHASH in uReport).
#### Java:

`sr_thread_get_duphash(crash_thread, 4, NULL, SR_DUPHASH_NORMAL);`

**Comment by xsuchy** [comment]
Can you elaborate on this issue? What you actually want to achieve?

**Comment by xsuchy** [comment]
I guess this is already implemented. Please reopen if you can elaborate.
