### ISSUE TITLE
Please add "Search" page

### ISSUE THREAD

**Issue by jfilak** [abrt/faf#382]
When I want to see particular problems I have to chose 'Problem' page and  wait several seconds to finish the rendering of default results. It would be nice if you could split 'Problem' page to 'Problem' page and 'Search' page. The latter page should have expanded 'Advanced filters' and should not submit any query upon loading.

**Comment by jfilak** [comment]
The page should have the date range filter set to maximum by default.

**Comment by sorki** [comment]
Waiting several seconds for problem page is resolved in master with query caching.

**Comment by xsuchy** [comment]
I agree, it is fast enough nowadays.
