### ISSUE TITLE
Advanced filters should stay open between queries when used

### ISSUE THREAD

**Issue by sorki** [abrt/faf#401]
When I fill one of the advanced filter fields and execute a query advance filter part is hidden and I have to click on Advance filter again to show it.

Would be nice to have it shown when used so user doesn't have to click on Advance filter over and over again when exploring problems.

**Comment by mbrysa** [comment]
It stays open for me, here's the code: https://github.com/abrt/faf/blob/master/src/webfaf2/templates/problems/list.html#L17

**Comment by sorki** [comment]
I see, the fields were missing.
