### ISSUE TITLE
Filter results based on package version

### ISSUE THREAD

**Issue by kalev** [abrt/faf#413]
When viewing problem reports in the web interface, I would appreciate a way to filter the results based on package version. When it comes to packages that are in the default install, a lot of people seem to be running older versions and that generates a lot of noise. Having a way to only view the results for the latest build would make my life much easier.

Thanks!

**Comment by jfilak** [comment]
Someone correct me if I'm wrong, but this is already implemented and deployed. On `Problems` page you can specify package versions in `Advanced filters`.

**Comment by kalev** [comment]
Ooh, sweet! I totally missed that. Thanks guys!
