### ISSUE TITLE
Release tracking bug

### ISSUE THREAD

**Issue by sorki** [abrt/faf#414]
We should improve our release cycle:
- document changes
- document APIs
- provide official repositories
- get faf packaged for Fedora
- release 1.0 version

As of now faf is slowly reaching mature state where handling these things should be possibly without much hassle.

**Comment by sorki** [comment]
http://keepachangelog.com/

**Comment by mmahut** [comment]
OpenShift Online team would welcome official EPEL-7 packages

**Comment by sorki** [comment]
Packages incoming!

More stuff
* have better readme
* have contribution guidelines

**Comment by xsuchy** [comment]
I think all of the above is done but one. Releasing to Fedora. And since we have Copr I would say it is not needed. So closing as done.

**Comment by sorki** [comment]
Well done!
