### ISSUE TITLE
Filter problems by bug status

### ISSUE THREAD

**Issue by mbrysa** [abrt/faf#416]
To improve problem filtering and further help problem prioritization, I believe these filters would be useful:
* Problem has a bug attached
* Problem has no bugs attached
* Problem has an open bug attached
* All the bugs in a problem are closed

**Comment by jfilak** [comment]
Your proposal sounds interesting. Wouldn't be also useful to be able to select problems having bug reports in more bug trackers? It could help CentOS maitainers in back-porting fixes from Fedora.
