### ISSUE TITLE
problem "state" column should have multiple CLOSED states

### ISSUE THREAD

**Issue by mistmist** [abrt/faf#429]
When searching for problems on https://retrace.fedoraproject.org/faf/, there is a "State" column.

It is slightly misleading, because it will display a green "CLOSED" if a bug has been closed in bugzilla.redhat.com in any way, including resolutions like CANTFIX or INSUFFICIENT_DATA that indicate the bug was not actually fixed (we use those often when the bugzilla reporter does not provide steps to reproduce).

The information is available by hovering over the individual bugzilla links in the next column, but that is quite inconvenient, there can be 5 or more bugzilla bugs per problem.

Please add another state there so we can differentiate between "closed-and-fixed" and "closed-but-still-buggy", so that "closed-and-fixed" is only displayed when there is at least one bug with ERRATA or NEXTRELEASE (or similar) resolution.

**Comment by mbrysa** [comment]
These are all the resolutions currently available:
```python
BUG_RESOLUTIONS = [
    "NOTABUG", "WONTFIX", "WORKSFORME",
    "DEFERRED", "CURRENTRELEASE", "RAWHIDE",
    "ERRATA", "DUPLICATE", "UPSTREAM", "NEXTRELEASE",
    "CANTFIX", "INSUFFICIENT_DATA", "EOL"
]
```
Could you please advise me which should be considered closed-but-still-buggy?

**Comment by jfilak** [comment]
Looking at https://fedoraproject.org/wiki/BugZappers/BugStatusWorkFlow I would use  NEXTRELEASE, CURRENTRELEASE, RAWHIDE and ERRATA for the closed-and-fixed.

However UPSTREAM does not necessary mean that the crash is not fixed.
