### ISSUE TITLE
Report <-> ReportBacktrace relation has to be m2m

### ISSUE THREAD

**Issue by mozeq** [abrt/faf#44]
Opened '20120827T16:49:42' by rmarko as https://fedorahosted.org/abrt/ticket/696

Currently, report can has multiple backtraces but two reports can't share the same backtrace which prevents backtrace de-duplication algorithm.

Enable de-duplication in pyfaf/retrace.py:~269 when this is fixed.

**Comment by xsuchy** [comment]
When we get report, how we find that the BT is the same as in other report. That is basicaly the de-duplication algorithm. So this issue is just shifting the work somewhere else, but does not solve anything. closing
