### ISSUE TITLE
Make uReport's OS version matching optional

### ISSUE THREAD

**Issue by jfilak** [abrt/faf#482]
For some operating systems we need to track bugs per minor release (Fedora - because of autoclosing of EOLed bugs) and for some systems we need to track  bugs per major release (RHEL).

The current implementation of algorithm deciding whether a uReport is known requires full OS version match, which is good for the former case [1]. 

Please make this feature configurable to enable tracking bugs per major release.

 Thank you for considering my request

1: https://github.com/abrt/faf/blob/master/src/webfaf/reports.py#L616

**Comment by marusak** [comment]
Isn't this duplicate of #489 which is already solved?
