### ISSUE TITLE
view abtr reports per machine

### ISSUE THREAD

**Issue by jsilhan** [abrt/faf#484]
Having occurrences of reports counted once per user is for developers better statistic which could better priories bug reports. I would like to see special view from web UI for this feature.

In Fedora all traffic should be anonymous so some local database with already reported crashes + sending a flag(whether it was already reported by this user or not) to the server can workaround mentioned issue. RFE was discussed and pre-approved by The Code Master (@jfilak)

**Comment by jfilak** [comment]
uReport has been enriched with 'serial' field. Its value should hold number of local occurrences. Report and Problem pages should display a histogram of these values. User should be able to get the number of affected machines from the colum for 1 which means "first occurrence on this machine". FAF should allow its users to filter out problems that by number of affected machines.

**Comment by jsilhan** [comment]
thx. So this issue could be closed then, right?

**Comment by jfilak** [comment]
Eh,  I am sorry for the confusion, those are my notes before we start working on it.

**Comment by patriczek** [comment]
We will add unique reports into current graphs (daily, weekly, monthly) history.

**Comment by patriczek** [comment]
![screenshot from 2016-10-03 14-08-01](https://cloud.githubusercontent.com/assets/4972932/19037476/bfa1d5a4-8976-11e6-8ff9-afea473d5021.png)
@jsilhan here is preview of graphs where are included unique reports per machine (for now only in daily graph), it's ok from your side or do you have any comments what to change?

**Comment by jfilak** [comment]
@patriczek I think the unique count should be everywhere we have Count and not only in the graphs.

**Comment by xsuchy** [comment]
This should be resolved for some time. I see a unique number in tables and in graphs.
