### ISSUE TITLE
FAF - Group reports

### ISSUE THREAD

**Issue by patriczek** [abrt/faf#489]
Curretnly FAF searches for a ureport by its hash. If the hash is found in the database and the hash record is associated with a bug report for the same os release as the report’s OS release, we return all associated Bugzilla bug reports and the received ureport is marked as known.

Request from QA Team A is to receive all associated bugzilla bugs for each submited ureport. Their goal is to open a bugzilla bug for each affected OS release. They consider a ureport known if there is a bugzilla bug for the ureport that have the exactly the same OS release as the urerport. However, they don’t need FAF to recognize duplicate by itself, they assest ABRT reports manually.

Request from QA Team B is to mark ureport as known if report with same OS Release, architecture and same version of packages exists and have associated an URL attachment and the URL points to a dump directory tarball uploaded to an FTP server. They are going to attach at least two types of URL - dump directory tarballs and test case reports.

We would have the following scenario:

If a FAF report has associated RHEL-7.0 and RHEL-7.1 bugs  and you send 
a duplicate report from RHEL-7.2, you will get those two bugzilla bugs. 
However, if you send a duplicate from RHEL-6.8, you will get empty list. 
If you then create a bugzilla bug for the RHEL-6.8 crash and associate 
the bug with the faf report and send a duplicate report from RHEL-7.2 again, you 
will get all the associated bugs (event the RHEL-6.8 one).

**Comment by patriczek** [comment]
We do not need to implement the “URL of type DumpDir” condition because we can rely on the fact that together with first received uReport of its kind a new dump directory will be uploaded on an FTP server too and the FTP URL will be attached to the ureport (uploading of dump directories to FTP will happen automatically). Hence if a received report meets the known criteria (OS Minor version | OS Architecture | Packages), we can assume that FTP URL already exists and it is not necessary to upload the dump directory again. However, in case of an error while uploading to FTP server, the report data will never be available.

In order to avoid special casing and make the algorithm configurable and reusable we can create a constant for every requested condition we need. These constants will be used as flags and will be used in logical disjunction:

Bug OS Minor version
Current behaviour - The report has attached a bug with equivalent OS Major version and OS Minor version
name: BUG_OS_MINOR_VERSION

Bug OS Major version
QA Team A request - The report has attached a bug with equivalent OS Major version
name: BUG_OS_MAJOR_VERSION

The same uReport was already received
QA Team B request:
uReport OS Major version match
AND uReport OS Minor version match
AND uReport OS Architecture match
AND Packages match
name: EQUAL_UREPORT_EXISTS

QA Team A needs only this:
BUG_OS_MAJOR_VERSION

QA Team B probably needs this :
 BUG_OS_MINOR_VERSION | EQUAL_UREPORT_EXISTS

**Comment by martinky82** [comment]
As a QA team B member, I deem the criteria described here sufficient. We can tweak it a little bit later, if necessary.

**Comment by martinky82** [comment]
In the first phase, we can omit the check for Packages so the criteria are as follows:

The same uReport was already received
QA Team B request:
uReport OS Major version match
AND uReport OS Minor version match
AND uReport OS Architecture match
name: EQUAL_UREPORT_EXISTS

**Comment by jfilak** [comment]
I believe this issue is fixed.
