### ISSUE TITLE
RFE: add [Back] button to the Associate bug.. screen

### ISSUE THREAD

**Issue by martinky82** [abrt/faf#491]
If user goes to the Associate bug .. screen directly by URL, the only way to go to the report itself is by deleting the 'associate_bz' part of URL. This is a bit inconvenient. Having a button to go up/back to the report would help.

**Comment by marusak** [comment]
Hi @Anisha1234 
I am happy to see your interest in this issue.
I believe you never tried running FAF, so I suggest starting by doing that. Please look into [HACKING](https://github.com/abrt/faf/blob/master/HACKING.md) and mainly [building images](https://github.com/abrt/faf/blob/master/HACKING.md#building-in-container) and [running them](https://github.com/abrt/faf/blob/master/HACKING.md#running-container-images) . If you can see running FAF on `http://localhost:8080/faf` you should try reporting a problem in there.

_note please, that following part works only on Fedora, CentOS and RHEL, for other distros it can be a bit (or even a lot) harder_

 Open a file `/etc/libreport/plugins/ureport.conf` as `root` and enter there:
`URL = http://localhost:8080/faf`
Now execute `will_abort` (comes from package `will-crash`)
Hopefully in a few minutes you could see a spike in the graph in FAF.

If it worked, now you should be able to understand this issue. 
Now you can navigate to `Reports -> 1 -> Associate Bug`
You should be at this URL `http://localhost:8080/faf/reports/1/associate_bz`.
Now if you open this URL directly, you are not able to get back to report `1`. And that is this issue. We just need to add reference on the report number in the text `Associate bug with report 1` that should point to the report itself.

So the result should look like this (try clicking the number):
Associate bug with report [1](http://localhost:8080/faf/reports/1)

I know its a lot of things that I mentioned, but feel free to contact us on #abrt on freenode IRC channel or even me directly if you have problems or questions.

**Comment by anapauladsmendes** [comment]
Hello! I'm Ana Paula, I'm from Brazil and I'm a Outreachy applicant . I'm beginner, but I have been development my skills in Python, Selenium, Django, HTML, CSS, JavaScript, DOM and JQuery. I had some experience with Java in the University. I love learn and I am very excited to participate this apply with amazing people. I'm interested in this project and this issue.

**Comment by marusak** [comment]
Hi @anapauladsmendes 
Happy to hear you are interested. On this issue already works @Anisha1234 so lets keep it to her. There are other issues you may work on. Contact me, if you need help with choosing a right issue.

**Comment by xsuchy** [comment]
> Can I make PR and suggest changes?

Definitely yes!

**Comment by Anisha1234** [comment]
@marusak As per your instructions, I have set up the FAF environment and I am able to navigate through the URL provided. But you have mentioned in the comment to "execute will_abort which comes from will-crash package". I would like to know more about it so that I can generate a spike in graph in FAF to generate the issue. Please help me out in this regard.

**Comment by Anisha1234** [comment]
@marusak with execution of `find /var/spool/faf/reports/` , I am able to see the folder /var/spool/faf/reports/incoming and a few more. But the incoming directory is empty. So in  local moachine at "/var/spool/abrt/cccp-*", I tried to execute `reporter-ureport -vvv`. but it is throwing me the error : 

> libreport global configuration contains unrecognized option : 'URL'
> Cannot continue without libreport global configuration.
> 
But I have already changed the URL at /etc/libreport/plugins/ureport.conf as `URL = http://localhost:8080/faf` as root. How should I fix it?

**Comment by marusak** [comment]
> ... but it is throwing the error...

hmm, weird. Can you please remove it from the config file and check that it gets reported to retrace.fedoraproject.org? And then please write it back there manually, don't copy it there, as you may copy some whitespace characters. If it does not work, can you please share your config file?

But also look into options of `reporter-ureport` and you will find out you can specify server directly on command line.

**Comment by Anisha1234** [comment]
@marusak I executed `reporter-ureport --url http://localhost:8080/faf` but it is still showing the same error.
I also removed the URL from config file and wrote it again. Still it is the same. This is my config  file at "/etc/libreport/plugins/ureport.conf"
[ureport.conf.txt](https://github.com/abrt/faf/files/2418893/ureport.conf.txt)

**Comment by marusak** [comment]
Can you write what version of `libreport-plugin-ureport` you have? And what OS? Can you also reinstall this package? (make sure that you replace the configuration file).

Anyway, I share one ureport, you can download it and put it into your FAF directly. It can be found [here](https://mmarusak.fedorapeople.org/43335030-7423-43b2-b49b-992913f773ba)

**Comment by dnuka** [comment]
Hi `FAF` community! 
I just got approved my initial application for Outreachy. Can I work on this issue? @marusak

**Comment by Riju19** [comment]
Can I take up this issue, in case nobody is working on it?

**Comment by crisloma** [comment]
Dear @Riju19, I hope this message finds you well. 
Are you still working on this issue? Could I help to solve it? 
Thanks,
Cristina

> 
> 
> Can I take up this issue, in case nobody is working on it?

**Comment by Riju19** [comment]
Hi! Yes, I am working on it.

**Comment by Riju19** [comment]
@marusak  Please review https://github.com/abrt/faf/pull/719
