### ISSUE TITLE
RFE - copy component from sumary page to problems page

### ISSUE THREAD

**Issue by stransky** [abrt/faf#498]
There's a graph of crashes on summary page:

https://retrace.fedoraproject.org/faf/summary/?opsysreleases=122&component_names=firefox&daterange=2016-03-30%3A2016-04-13&resolution=d

when I click on actual day I'm redirected to "problems" page. I'd like to keep selection criteria. Release (Fedora 24) is kept but component (firefox) is deleted and there's a list of issues from all components. But I'd like to investigate only firefox bugs from the selected day.

**Comment by marusak** [comment]
This is a simple fix (see my commit). However I am not sure if the problem page is the correct choice. Shouldn't this redirect to report page, since summary displays reports? mainly asking @sorki

**Comment by xsuchy** [comment]
I would, personally, prefer the problems. Closing as the preference is now preserved.
