### ISSUE TITLE
faf accepting reports from "atom" editor not in Fedora

### ISSUE THREAD

**Issue by nirik** [abrt/faf#525]
Someone noted: 

https://retrace.fedoraproject.org/faf/reports/1243368/

which is against the github atom editor. Since thats not in Fedora should it be accepting reports for it?

**Comment by jfilak** [comment]
Since there isn't any package of that name, FAF should refuse to accept such a report. But it apparently didn't, so we must find out why.

**Comment by mtoman** [comment]
This is the intended behavior, FAF accepts every report it gets (given it passes sanity checks), it just filters out non-fedora components in default views. You can get reports for components like vlc, ffmpeg, VirtualBox-5.0 etc. by explicitely asking for them. There are no debuginfos though so advanced features like retracing and clustering likely do not work properly for those.

**Comment by nirik** [comment]
ok. I will pass this along to the person that reported it. 

Thanks for the quick answer.

**Comment by marusak** [comment]
@mtoman so it is not a bug. Can this issue be closed?

**Comment by mtoman** [comment]
Sure, this should have been closed a while ago
