### ISSUE TITLE
send ABRT report email notification per machine

### ISSUE THREAD

**Issue by jsilhan** [abrt/faf#532]
this is follow up from issue https://github.com/abrt/faf/issues/484 . As a developer it's more important for me to see in email reports number of occurrences per machine. Is it possible to change it in email notifications, please? Probably it should report with higher cadence then. I.e. instead of notification about of 10, 100, 1000, ... abrt reports send email twice as often - 10, 50, 100, 500, 1000, ...

**Comment by sorki** [comment]
How hard it is to spell the name of the ABRT project correctly? Also this is not abrt, not abtr and not even abrt server. It's FAF.

**Comment by marusak** [comment]
I think that this was already solved, wasn't it? @jfilak

**Comment by marusak** [comment]
Closing as I believe it was done. If I am wrong, feel free to reopen and explain what needs to be done.
