### ISSUE TITLE
Change component

### ISSUE THREAD

**Issue by xsuchy** [abrt/faf#551]
E.g. for this report:
https://retrace.fedoraproject.org/faf/reports/1552061/
it is false that it belong to ruby component. It will be nice if user can change the component.

**Comment by jfilak** [comment]
Associate the report with a bugzilla bug and change Component of the bugzilla bug.

**Comment by jfilak** [comment]
https://fedoraproject.org/wiki/Automatic_Bug_Reporting_Tool
