### ISSUE TITLE
Make it possible to file bugs from Faf

### ISSUE THREAD

**Issue by lhirlimann** [abrt/faf#572]
at https://retrace.fedoraproject.org/faf/reports/1707013/ there is no link to open an issue, would be nice to be able to do so. Mozilla's socorro does that and it's very neat.

**Comment by xsuchy** [comment]
When you are logged in, there is button "associate bug". When you click on it, you may enter number of existing bug or create new one.

**Comment by marusak** [comment]
![associate](https://cloud.githubusercontent.com/assets/12330670/25989016/b95ae244-36fa-11e7-97c1-7c3a7d56c5ef.png)

There is picture how it looks like. If you are logged in and cannot see this button that means that you do not have permission - only maintainers of the crashing component can do that.
