### ISSUE TITLE
Accept archives with miliseconds

### ISSUE THREAD

**Issue by marusak** [abrt/faf#592]
Accept archive with name
ccpp-2017-10-02-14:23:33.710433-1359.tar.gz

**Comment by vorburger** [comment]
@marusak thanks for looking into this! 

Just FTR: This archive name is how "Problem Reporting" in Fedora 26 creates it (not a manually modified version).

**Comment by gayathrirajendar** [comment]
Hello @marusak ,

Let me please work on this issue. Can you please help me understand this better?

I was able to setup FAF and after your help, now I am able to get the reports by uploading it.

When I did try earlier, I got this from the `invalidureports` table.

`Element 'os' is invalid: Element 'name' is invalid: Only the following values are allowed: fedora, centos`

And I am using RHEL 7.4

Thanks for the help.

**Comment by marusak** [comment]
Hi @gayathrirajendar 
by default RHEL is not supported in provided images. You may write your [own plugin](https://github.com/abrt/faf/wiki/Operating-System-Plugins) but its a lot of work. Simpler would be to just use some other ureport. Look into https://github.com/abrt/faf/pull/713, I explain there how to report and also provide link for some ureport. (May even upload it manually through http://localhost:8080/faf/reports/new/)

Anyway, for this issue it is not necessary to  have any report.
Explaining fully what is emergency reporting is for a longer time, but lets just focus how to reproduce this issue and what needs to be done.
If you created any crash on your computer, you should be able to run `reporter-upload -d <dumpdir> -u http://localhost:8080/faf/dumpdirs/new/` where <dumpdir> replace by the path to a problem directory (/var/spool/abrt/cccp...).
From the output of this tool you should be able to see what archive was created. Also the tool should provide you with URL and if you open it, you should be able to see your archive.
Also you can create the archive by yourself (just tar.gz the whole dumpdir) with the same name and then try to upload it to `http://localhost:8080/faf/dumpdirs/new/`. Possibly it wont be accepted (maybe on RHEL 7.4 it will be, let me know).

But in my case it created name `ccpp-2018-09-20-21:15:55.518467-11870.tar.gz` which is not accepted. Look into code and find where the name is checked. Its done by regex. I think we should not be that strict about the end of the name, and accept anything that starts as type-year-month-day-hour:minutes:seconds followed by any combination of numbers with dots and dashes.

**Comment by marusak** [comment]
@gayathrirajendar thank you for the PR, I'll review it.

>    Can you please tell me how to run a specific test when we are using the container images?

When you build development image, all tests are run. To run a specific test, you can change to the directory where the test is and execute it. For example to run test_dumpdirs do:
`cd tests/test_webfaf/`
`./test_dumpdirs.py`
You can also do it in the container the same way (the whole FAF repo gets copied into the container)
