### ISSUE TITLE
Does FAF need BZ comments and  attachments?

### ISSUE THREAD

**Issue by marusak** [abrt/faf#595]
What does it FAF use for? How important is it for FAF? It seems to me, that it only takes up space (around 10GB on retrace.fedoraproject.org - it is not too much, but I am trying to understand what is used for)
@sorki @jfilak  ?

**Comment by jfilak** [comment]
Not sure. Remove them and you will see :)

In the history, ABRT services used to add automatic comments. Those comments could be parsed out and some important information could be gathered from them. Full featured backtrace is an example of such an important information - but that's history.

@mtoman Do you remember why FAF needs BZ comments?

**Comment by mtoman** [comment]
I have two equally probable theories :)
1) They were used to match duplicates, because marking a bug as a duplicate creates a comment which is persistent even if the bug changes state later on and somebody changes/removes the duplicate field.
2) It was sort of feature-completeness thing - the first versions of FAF did not know what data they would use in the future so they cached everything they could.

**Comment by mtoman** [comment]
Actually
3. in very early versions, before uReports, FAF could have been looking for comments from ABRT and use them to reconstruct the metadata that are now sent in uReports

**Comment by marusak** [comment]
Thank you for clarification. Can it be removed? Or should we keep it and only add config option not to save those data?

**Comment by jfilak** [comment]
Remove the comments and attachments (you have several terrabytes of backups), turn of the feature, don't remove the feature from code, good plan?

**Comment by marusak** [comment]
> Remove the comments and attachments (you have several terrabytes of backups), turn of the feature, don't remove the feature from code, good plan?

What do you mean by `turn off`? With config, or remove calling the function, which does this saving? (and keep implemented functions for saving these thinks).
