### ISSUE TITLE
URGENT! improve link ordering of External URLs

### ISSUE THREAD

**Issue by vbenes** [abrt/faf#598]
External URLs are super mess.

it's absolutely insane to look for something in external links.
https://url.corp.redhat.com/ad15b94

Would it be possible to sort it time wise? I would prefer to see the newest at the top. So time wise in reverse order. Maybe some sort of separator may be handy too (to separate single report)

Thanks,
Vladimir

**Comment by marusak** [comment]
> Would it be possible to sort it time wise? I would prefer to see the newest at the top. So time wise in reverse order.

Sure, this is one-line fix, since we already save the date, see:
https://github.com/abrt/faf/blob/master/src/pyfaf/storage/report.py#L579
I'll do it ASAP.

> Maybe some sort of separator may be handy too (to separate single report)

Can you elaborate on this more?

**Comment by marusak** [comment]
@vbenes I open PR #600 , which fixes this issue. I hope I understood what you were requesting. Please see the following screenshot. Does it work as you expected? Let me know what would you changed, added or what was misunderstood.

![urls](https://user-images.githubusercontent.com/12330670/32949069-bd0ca490-cba1-11e7-94a0-a0fc96c2a7a0.png)

**Comment by vbenes** [comment]
It looks good. Will the newest report links be on top or the other way around?

**Comment by marusak** [comment]
The newest will be on top. You can see it in the image, The URLS have been send in order first, second, third... so seventh is the newest one.

**Comment by vbenes** [comment]
perfect! that's preferred ordering indeed :-)

**Comment by xsuchy** [comment]
Please add there (i) with bubble which state: URLs are grouped by reports.
