### ISSUE TITLE
allow removing already associated bugs

### ISSUE THREAD

**Issue by vbenes** [abrt/faf#599]
when I accidentally associated NOTABUG and would like to remove it, no way.

I think we should see associated bugs and we should be able to remove them

thx

**Comment by marusak** [comment]
This is currently WIP by an external student. I'll let you know about the progress.

**Comment by anapauladsmendes** [comment]
Hello! I'm Ana Paula, I'm from Brazil and I'm a Outreachy applicant . I'm beginner, but I have been development my skills in Python, Selenium, Django, HTML, CSS, JavaScript, DOM and JQuery. I had some experience with Java in the University. I love learn and I am very excited to participate this apply with amazing people. I'm interested in this project and this issue. Could you explain more about the it?

**Comment by marusak** [comment]
Hi @anapauladsmendes 
if you look at some problem, it may happen this problem has an external bug assigned. (for example https://retrace.fedoraproject.org/faf/problems/428460/)
It is possible to assign these problems if you are maintainer of the given package, but I don't think you can see this option on retrace.fedoraproject.org/faf but if you deploy your own FAF development container[1], by default you are admin there and therefore should be able to see button 'Associate bug' at any given report. If you assign such report you may realize you assigned a wrong one and therefore decide to remove it - however this is not implemented quite yet - and therefore this issue.

It would be nice to extend the page to which you are redirected after you click 'associate bug' button with list of already associated bugs and add some trash icon next to them to remove those. The specific details are left to the developer to propose solutions.

[1] https://github.com/abrt/faf/blob/master/HACKING.md#running-container-images

**Comment by 14Richa** [comment]
Hi @marusak any updates on this? I was looking to send my first PR. All other issues seems to have people working on them. @anapauladsmendes Have you made progress on this? Would you like us to work together maybe. Cheers :)

**Comment by anapauladsmendes** [comment]
Hi, @14Richa I needed to abandon the Outreachy process now, you can solve this issue. Good luck!

**Comment by laurenolivia** [comment]
@marusak Hi Matej, I'm an Outreachy applicant and recent graduate of a coding bootcamp. I see this issue may be taken and if so, could you please point me in the direction of a newcomer-friendly PR?

**Comment by Prabhleen9Kaur** [comment]
@marusak Hi I am an outreachy aspirant i was looking for an issue to work as this issue is already taken up ,can you suggest me some other issue.
