### ISSUE TITLE
faf-migrate-db usage issue

### ISSUE THREAD

**Issue by mjtrangoni** [abrt/faf#614]
Hi, 
I did update from `v0.12.408_g8de39e1`to [epel-7-x86_64/00724330-faf](https://copr-be.cloud.fedoraproject.org/results/%40abrt/faf-el7/epel-7-x86_64/00724330-faf/) aka. `1.3.0-1`.

Could you please help me with the DB migration? I know, I have to use `faf-migrate-db` but a `$ faf-migrate-db --revision head` does not seem to be working.

I see for example,

```
$ faf repoinfo centos74_repo
Name: centos74_repo
Type: yum
CRITICAL:faf:Action failed unexpectedly: ProgrammingError: (ProgrammingError) relation "urls" does not exist
LINE 2: FROM urls, urlrepo
             ^
 'SELECT urls.id AS urls_id, urls.url AS urls_url \nFROM urls, urlrepo \nWHERE %(param_1)s = urlrepo.repo_id AND urls.id = urlrepo.url_id' {'param_1': 1}
```

**Comment by marusak** [comment]
Update: as you edited your post with:

> I did have this issue the last time, see #543.

I can see two reasons why this may not work...
1) You used `--stamp-only` as it seems you did in the previous issue, then it could be simple fix
2) You used some other migration (as presented in that issue) and now it does not fit into the tree. Possibly I can see that you used migration `168*` after `183*` but in upstream we have one more migration between them (the one with urls table). You can check that - can you look into DB what schema does table `bzbugs` has? `sudo -u faf psql faf` and `\d bzbug` (I want to know, if it has column `private`)

**Comment by mjtrangoni** [comment]
Hi @marusak ,

Sorry for the delay, I have no `private` column.

```
faf=> \d bzbugs
                                        Table "public.bzbugs"
      Column      |            Type             |                      Modifiers
------------------+-----------------------------+-----------------------------------------------------
 id               | integer                     | not null default nextval('bzbugs_id_seq'::regclass)
 summary          | character varying(256)      | not null
 status           | bzbug_status                | not null
 resolution       | bzbug_resolution            |
 duplicate        | integer                     |
 creation_time    | timestamp without time zone | not null
 last_change_time | timestamp without time zone | not null
 tracker_id       | integer                     | not null
 opsysrelease_id  | integer                     | not null
 component_id     | integer                     | not null
 whiteboard       | character varying(256)      | not null
 creator_id       | integer                     | not null
Indexes:
    "bzbugs_pkey" PRIMARY KEY, btree (id)
    "ix_bzbugs_component_id" btree (component_id)
    "ix_bzbugs_creator_id" btree (creator_id)
    "ix_bzbugs_duplicate" btree (duplicate)
    "ix_bzbugs_opsysrelease_id" btree (opsysrelease_id)
    "ix_bzbugs_tracker_id" btree (tracker_id)
Foreign-key constraints:
    "bzbugs_component_id_fkey" FOREIGN KEY (component_id) REFERENCES opsyscomponents(id)
    "bzbugs_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES bzusers(id)
    "bzbugs_duplicate_fkey" FOREIGN KEY (duplicate) REFERENCES bzbugs(id)
    "bzbugs_opsysrelease_id_fkey" FOREIGN KEY (opsysrelease_id) REFERENCES opsysreleases(id)
    "bzbugs_tracker_id_fkey" FOREIGN KEY (tracker_id) REFERENCES bugtrackers(id)
Referenced by:
    TABLE "bzattachments" CONSTRAINT "bzattachments_bug_id_fkey" FOREIGN KEY (bug_id) REFERENCES bzbugs(id)
    TABLE "bzbugccs" CONSTRAINT "bzbugccs_bug_id_fkey" FOREIGN KEY (bug_id) REFERENCES bzbugs(id)
    TABLE "bzbughistory" CONSTRAINT "bzbughistory_bug_id_fkey" FOREIGN KEY (bug_id) REFERENCES bzbugs(id)
    TABLE "bzbugs" CONSTRAINT "bzbugs_duplicate_fkey" FOREIGN KEY (duplicate) REFERENCES bzbugs(id)
    TABLE "bzcomments" CONSTRAINT "bzcomments_bug_id_fkey" FOREIGN KEY (bug_id) REFERENCES bzbugs(id)
    TABLE "bzcomments" CONSTRAINT "bzcomments_duplicate_id_fkey" FOREIGN KEY (duplicate_id) REFERENCES bzbugs(id)
    TABLE "reportbz" CONSTRAINT "reportbz_bzbug_id_fkey" FOREIGN KEY (bzbug_id) REFERENCES bzbugs(id)
```

**Comment by marusak** [comment]
What is output of `ls /usr/lib/python2.7/site-packages/pyfaf/storage/migrations/versions/*.py | wc -l`
and `cd /usr/lib/python2.7/site-packages/pyfaf/storage/migrations` followed by `alembic heads`?

**Comment by mjtrangoni** [comment]
Hi @marusak ,
```
# ls /usr/lib/python2.7/site-packages/pyfaf/storage/migrations/versions/*.py | wc -l
26
# cd /usr/lib/python2.7/site-packages/pyfaf/storage/migrations; alembic heads
acd3d9bf85d1 (head)
```

**Comment by marusak** [comment]
Then I think that you ran 'faf-migrate-db --stamp-only`. Is it possible? If so, than it can be a simple fix.
If not, than we have to assume that something crashed and more investigating will be needed.

**Comment by mjtrangoni** [comment]
@marusak mmm I think, I did it. What is the simple fix then?

**Comment by marusak** [comment]
Ok, just to inform you - you run with `--stamp-only` just for the first time when you have new and clean DB. If you already have some data in it, you don't want to run this.

The last migration you have done was the one as described in #543?
If so, than we know the last version, if not, we need to find this version manually.

If it was, than you need to put `183a15e52a4f` into table `alembic_version`. Then you can run `faf-migrate-db --revision head`.

(I am a little bit afraid that the migration may fail, but lets see)

**Comment by mjtrangoni** [comment]
@marusak Thanks, It works!
``faf=> UPDATE public.alembic_version SET version_num='183a15e52a4f';
$ faf-migrate-db --revision head
INFO:alembic.runtime.migration:Context impl PostgresqlImpl.
INFO:alembic.runtime.migration:Will assume transactional DDL.
INFO:alembic.runtime.migration:Running upgrade 183a15e52a4f -> 1c4d6317721a, Support mirror urls in repositories
INFO:alembic.runtime.migration:Running upgrade 1c4d6317721a -> 168c63b81f85, report_history_default_value
INFO:alembic.runtime.migration:Running upgrade 168c63b81f85 -> acd3d9bf85d1, Ignore private bugzilla bugz
```

**Comment by marusak** [comment]
Happy to hear that:)
