### ISSUE TITLE
faf reposync: ERROR:faf.RepoSync:No valid mirror for repository 'centos74_repo'

### ISSUE THREAD

**Issue by mjtrangoni** [abrt/faf#616]
Hi,

After upgrading to `v1.3.0` I am having a problems with the `reposync` command. See,

```
faf@xxxx ~ $ faf repoinfo centos74_repo
Name: centos74_repo
Type: yum
URL: http://yum/centos/7.4/x86_64/os_and_updates/
GPG check enabled: False
faf@xxxx ~ $ faf -d -v reposync >> /var/log/faf/reposync.log
DEBUG:faf:Registering System plugin 'centos': CentOS
DEBUG:faf:Registering System plugin 'fedora': Fedora
[...]
DEBUG:faf:Registering ProblemType plugin 'ruby': RubyProblem
DEBUG:faf:Registering SolutionFinder plugin 'sf-prefilter': PrefilterSolutionFinder
DEBUG:faf:Registering SolutionFinder plugin 'sf-probable-fix': ProbableFixSolutionFinder
INFO:faf.RepoSync:Processing parametrized repo 'centos74_repo'
ERROR:faf.RepoSync:No valid mirror for repository 'centos74_repo', skipping
```

This has been working previously at v0.12.0 without problems. What can I check? What does this error mean exactly?

Thanks!!

**Comment by marusak** [comment]
It points to `http://yum/centos/7.4/x86_64/os_and_updates/` which is definitely not a repository. 
If you did not put it there, then I am very curious how it get in there.
Anyway, what URL you wanted to have there?

You can use `repomod` action to fix the url. Maybe you should also use `check-repo` to check that all repositories are valid.

**Comment by mjtrangoni** [comment]
Hi @marusak, 
This is one of our private yum repositories. What did you mean with `which is definitely not a repository`?

By the way I have, 
```
faf@xxxx ~ $ faf check-repo                                                             
'centos74_repo' is not assigned with OpSys release.
There are some problems, please resolve them
```
which is new to me.

How can I assign this to CentOS?

**Comment by marusak** [comment]
so you can connect to `http://yum/centos/7.4/x86_64/os_and_updates/` and `http://yum/centos/7.4/x86_64/os_and_updates/repodata`? If so, then it should work just fine.

> How can I assign this to CentOS?

Yeah, that is a new feature. You can do it with action `repoassign`.

**Comment by mjtrangoni** [comment]
And how can I skip this?
```
$ faf repoassign centos74_repo CentOS
ERROR:faf.RepoAssign:Assigning operating system without release to non - parametrized repo. Assign operating system with release.
$ faf releaselist
CentOS 7
$ faf opsyslist
Red Hat Enterprise Linux
Fedora
CentOS
```

**Comment by marusak** [comment]
`faf repoassign centos74_repo "CentOS 7"`

**Comment by mjtrangoni** [comment]
Ok, now is `check-repo` happy, but `reposync` isn't. See,
```
faf@xxxx ~ $ faf check-repo
Everything is OK!
faf@xxxx ~ $ faf repoinfo centos74_repo
Name: centos74_repo
Type: yum
URL: http://yum/centos/7.4/x86_64/os_and_updates/
GPG check enabled: False
faf@xxxx ~ $ faf reposync >> /var/log/faf/reposync.log
INFO:faf.RepoSync:Processing parametrized repo 'centos74_repo'
ERROR:faf.RepoSync:No valid mirror for repository 'centos74_repo', skipping
```

**Comment by marusak** [comment]
Ok, it seems that you have assigned opsys to it, event though it is not necessary. You should remove link between CentOS and that repository, but keep "Centos 7" to that repo. You need to do it in the db directly.
You want to remove that line in table `opsysrepo`

**Comment by mjtrangoni** [comment]
Hi @marusak,

I removed the old repository definition, and added a new one, and this is running now, see,
```
$ faf reposync >> /var/log/faf/reposync.log
INFO:faf.RepoSync:Processing repo 'centos7' assigned with OpSysRelease
INFO:faf.RepoSync:Processing repository 'centos7' URL: '([u'http://yum/centos/7.4/x86_64/os_and_updates/'],)'
```

Thank you!

**Comment by marusak** [comment]
Happy to hear that it works:)
