### ISSUE TITLE
Statistics pages timeout

### ISSUE THREAD

**Issue by abitrolly** [abrt/faf#618]
Statistics URLs time out after 10s

https://retrace.fedoraproject.org/faf/stats/today/
https://retrace.fedoraproject.org/faf/stats/yesterday/
...

**Comment by marusak** [comment]
Does it work for you now? (it is cached now) It works for me just fine, but maybe slower connection can be problem?

**Comment by abitrolly** [comment]
No, it doesn't.

**Comment by mkutlak** [comment]
Works fine for me.

Closing.
