### ISSUE TITLE
Session closed when I click with the mouse on the ON/OFF buttons of the Lock Keys extension.

### ISSUE THREAD

**Issue by aldogiga** [abrt/faf#686]
I use the Lock keys extension that shows the status of the Numlock and Capslock on the panel.
If I click with the mouse on the ON/OFF switch of the Lock keys extension the session is closed and I have to login again. 
It is repeatable.
Note: may be relevant that before this behavior the session was locked (by screensaver) with the Caps lock key on and I had to change the status with the hard key of the keyboard in order to input correctly the password.
When the session was resumed the Caps lock were off but the Lock Keys indicator showed ON and when I tried to change the session was reset.

**Comment by marusak** [comment]
Hi,
are you talking about this https://extensions.gnome.org/extension/36/lock-keys/ ?
And what session you mean? This, `FAF`, is a service, that collects bugs and is accessible from https://retrace.fedoraproject.org/faf/summary/ . Do you mean session, as when you are logged in https://retrace.fedoraproject.org/faf/summary/, or you mean session as on your computer.

**Comment by marusak** [comment]
Ok, so as I suspected - FAF is only collecting problems, that happen in Fedora. You probably want to open bug against that extension (possible duplicate https://github.com/kazysmaster/gnome-shell-extension-lockkeys/issues/32).
