### ISSUE TITLE
Explain why associating bugs failed

### ISSUE THREAD

**Issue by marusak** [abrt/faf#710]
If I use web UI to associate bug to a report often it happens that it is rejected but only a generic message is displayed. It is frustrating to use. Often the reason is different opsys, different components etc.
Lets show this information to user so it easier to understand what is happening.

**Comment by gayathrirajendar** [comment]
Hello @marusak, 

I am very much curious to understand this issue. Regarding this issue, When I click on `Associate Bug` and even put a random bug ID from googling rhel-bugzilla and submit, I get 

`Failed to fetch bug. + <Some additional message>`.  
& 
`Internal Server Error. This error has been logged and we will take care of it soon. Sorry. `

I thought if I can read the error trace, I can understand something more. I tried the following,

In the docker folder, `docker logs --follow faf`. I couldn't see any additional logs there for the internal server error. Looks like I am checking it in the wrong place for internal server errors.

For the other error, 

After searching in many places, I could see the same error messages in the end of the `httpd_error_log` file in `/var/log/faf`. For my different attempts of associating a bug, different error message has come and all the times the message came in the UI too.

With my little above understanding, if you can please direct and connect me with this issue, I will be so glad to take it up.

**Comment by marusak** [comment]
Ok, sorry for delayed answer. I looked at it yesterday and I was surprised with the behavior, which was as you wrote, but different from what I thought it should be. To see this issue pick either `fedora-bugzilla` or `rhel-bugzilla`. The issue you are getting is related to #695.

When you try to pull random bug from bugzillas, you only get `Failed to fetch bug` message. You may try to pull the same bug in cmdline with `sudo -E -u faf faf pull-bug` to get better error messages. It should be easier to know why it is failing even from the webUI.

**Comment by gayathrirajendar** [comment]
Thanks @marusak .

At this [point](https://github.com/abrt/faf/blob/2976d8af955a8eb25ec7b0a2d9f7eba75ad8c74b/src/webfaf/reports.py#L650), looks like the bug is coming as None without raising an error (exception) and so it directly goes [here](https://github.com/abrt/faf/blob/2976d8af955a8eb25ec7b0a2d9f7eba75ad8c74b/src/webfaf/reports.py#L666). 

Can you please tell me where to find our print lines and debug logs in the container? It shall help me play with it and understand it better.

I am willing to work on and submit a PR for this issue. Shall I ?

**Comment by marusak** [comment]
> At this point, looks like the bug is coming as None without raising an error (exception) and so it directly goes here.

Yeah, I think you are right. We should probably raise exception or return error information (maybe as tuple?), why the function `download_bug_to_storage_no_retry` failed.

> Can you please tell me where to find our print lines and debug logs in the container? It shall help me play with it and understand it better.

by `print lines` you mean? As if you put somewhere `print("foo")`? I am afraid that if you put it in  `faf/src/webfaf/reports.py` it gets lost. I am not even sure about debug logs, as the server is not run in debug mode - but can be changed, see https://github.com/abrt/faf/blob/2976d8af955a8eb25ec7b0a2d9f7eba75ad8c74b/src/webfaf/webfaf_main.py#L28 

When I want to see outputs from somewhere I just raise it, such as `raise Exception("foo")` and then it is in `/var/log/faf/httpd_error_log`. (You sometimes may need to restart the container (`docker restart faf`) so it takes effect.

> I am willing to work on and submit a PR for this issue. Shall I ?

definitely
