### ISSUE TITLE
Unowned __pycache__ directories 

### ISSUE THREAD

**Issue by mkutlak** [abrt/faf#721]
After uninstallation faf leaves behind `__pycache__` directories since https://github.com/abrt/faf/pull/720.

```
bash-4.4# rpm -qf __pycache__
file /usr/lib/python3.7/site-packages/pyfaf/__pycache__ is not owned by any package
```

__Example:__
https://github.com/abrt/faf/blob/0be622120eaab177bd3b7ffecac089a4b045d4ce/faf.spec.in#L837
Should be changed to 
```
%{python3_sitelib}/pyfaf/__pycache__
%{python3_sitelib}/pyfaf/__pycache__/__init__.*.pyc
```

https://fedoraproject.org/wiki/Packaging:UnownedDirectories
https://fedoraproject.org/wiki/Packaging:Python#Byte_compiling

**Comment by ari3s** [comment]
I will fix this issue that is related to more directories.

**Comment by mkutlak** [comment]
Closed by https://github.com/abrt/faf/pull/727
