### ISSUE TITLE
Issues with Celery

### ISSUE THREAD

**Issue by mkutlak** [abrt/faf#724]
__How to run celery tasks with faf container:__
1) Download `redis` docker image
```
docker pull redis:latest
```
2) Start `redis` container with `hostname` and opened port `6379`:
```
docker run --name faf-redis --hostname faf-redis -dit -p 6379:6379 redis
```
3) Create `faf-network` and connect `faf` and `faf-redis` containers to it:
```
docker network create faf-network
docker network connect faf-network faf
docker network connect faf-network faf-redis
```
4) Change `hostname` in celery configuration to point to the `faf-redis` container:
```
docker exec faf sed -ie 's/localhost/faf-redis/g' /etc/faf/plugins/celery_tasks.conf
```
5) Restart `faf` container 
```
docker restart faf
```

Lot of the actions is not working on the `faf/celery_tasks/` page.

I see a lot of `TypeError: can't pickle generator objects` in logs.

**Comment by michalfabik** [comment]
Resolved in PR #804.
