### ISSUE TITLE
Kernel-core recoverable error 4.20.13-200.fc29.x86_64

### ISSUE THREAD

**Issue by Cpiral** [abrt/faf#762]
SW: Fresh install (just downloaded Fedora Workstation today).   Upgraded.   (Took 1.2GB to upgrade it!)
 4.20.13-200.fc29.x86_64
HW: Lenovo (Edge) Twist u230s, latest bios.

Context: Waking from sleep using spacebar.   Firefox was open with two windows (4 tabs each).

**Comment by ernestask** [comment]
This tracker is only for issues with faf. If the notification for the error came from ABRT, then please use ABRT to report it to the right place.
