### ISSUE TITLE
Bug 1481984 is still present in abrt in Fedora 30 

### ISSUE THREAD

**Issue by charlie-gorman-tierconnect-com** [abrt/faf#838]
Bug 1481984 - Unable to upload kerneloops: uReport data is invalid 
is still present in fedora 30 (https://bugzilla.redhat.com/show_bug.cgi?id=1481984) 
I can post my ureport -vvv output but it is no different than what has been already been reported on the BZ

**Comment by charlie-gorman-tierconnect-com** [comment]
because this bounces of the sever (encountered in both the web portal and automatic reporting) i'm less inclined to pin this on satyr as mentioned in the BZ

**Comment by ernestask** [comment]
Don’t create issues about Bugzilla bugs, just comment there.

I fixed one case recently: https://github.com/abrt/satyr/commit/c9f7d3c5b5e4cc546c2c940a1f28e68045cfcf24

Do upload the output from `reporter-ureport`, because “it is no different than what has already been reported” is not helpful.
