### ISSUE TITLE
Python: display exception message in webui

### ISSUE THREAD

**Issue by FelixSchwarz** [abrt/faf#856]
When a Python exception is recorded the retrace webui only shows the call stack but not the full exception. In particular the exception message is not shown.

This might be a duplicate of #216 but I'm not sure so I filed a new ticket.

Basically I need the crucial last line of a default Python traceback print (in #216 this is `ValueError: invalid literal for int() with base 10: ''`) somewhere even when the user did not file a bugzilla issue.

**Comment by mkutlak** [comment]
```
Why not to include the message from python exception? 
Think about the following: 
ValueError: 
invalid literal for int() with base 10: 'my_secret_password' uh oh!
```

https://github.com/abrt/faf/wiki/uReport#anonymity

**Comment by FelixSchwarz** [comment]
Ok - I can understand that decision but it renders abrt reports for Python almost useless. :-/

As this seems to be a conscious design decision I'll close this issue.
