### ISSUE TITLE
 webcam

### ISSUE THREAD

**Issue by minimaks6** [abrt/faf#885]
kernel  core  problem

**Comment by ernestask** [comment]
Can you please be a bit more specific about the issue you’re having?

**Comment by StykMartin** [comment]
This is an interesting issue. How can I reproduce it

**Comment by renanrodrigo** [comment]
me neither

**Comment by xsuchy** [comment]
I am looking for a page where 20 local beautiful kernels are hanging on webcam and eager to meet me, but I cannot find any :(

**Comment by minimaks6** [comment]
FIXED  
            
          
     
      
       
        Dnia 9 marca 2020 10:18 Ernestas Kulik &lt;notifications@github.com&gt; napisał(a):
       
    
       
         Can you please be a bit more specific about the issue you’re having?

**Comment by minimaks6** [comment]
fixed kernel core prob  
            
          
     
      
       
        Dnia 9 marca 2020 10:53 Martin Styk &lt;notifications@github.com&gt; napisał(a):
       
    
       
         This is an interesting issue. How can I reproduce it

**Comment by minimaks6** [comment]
fixed- kernel core prob  
            
          
     
      
       
        Dnia 9 marca 2020 10:58 Renan Rodrigo &lt;notifications@github.com&gt; napisał(a):
       
    
       
         me neither

**Comment by minimaks6** [comment]
Nice one , I fixed kernel core prob finally   
            
          
     
      
       
        Dnia 9 marca 2020 11:27 Miroslav Suchý &lt;notifications@github.com&gt; napisał(a):
       
    
       
         I am looking for a page where 20 local beautiful kernels are hanging on webcam and eager to meet me, but I cannot find any :(
