### ISSUE TITLE
cannot determine beaker job from FAF results

### ISSUE THREAD

**Issue by psklenar** [abrt/faf#901]
http://faf.lab.eng.brq.redhat.com/faf/problems/bthash/?bth=2bbf340e38d7b1981c974b003f2f68ec7aa00352&bth=31bcfd57b74bf792b41b8c93e3a6f07505307463&bth=7fb474980b025b5777eeed38c35e20752b14f946&bth=8cd1a05f22d206680124bb83f215dfd0d8827531&bth=d4a5d271ea35204d67437def2ef781c2501f522a&bth=fd37c392c026f3834ea1e4891ed22b9a0593cd3b

cannot determine beaker job

**Comment by ernestask** [comment]
We do not handle internal instances upstream.
