### ISSUE TITLE
Migrate to Werkzeug 1.0

### ISSUE THREAD

**Issue by ernestask** [abrt/faf#905]
https://werkzeug.palletsprojects.com/en/0.16.x/contrib/cache/ (cachelib not packaged in CentOS/EPEL/Fedora, so, enjoy)
https://github.com/abrt/faf/blob/5faf98d3def3d08551ea3689179591bfcb9251ae/src/webfaf/webfaf_main.py#L14

https://werkzeug.palletsprojects.com/en/0.16.x/contrib/fixers/
https://github.com/abrt/faf/blob/5faf98d3def3d08551ea3689179591bfcb9251ae/src/webfaf/webfaf_main.py#L12

Moreover, the spec file needs to be updated to reflect the dependence.

**Comment by xsuchy** [comment]
Should be IMHO reported as bug to https://apps.fedoraproject.org/packages/python-werkzeug/bugs/
