### ISSUE TITLE
Docker images do not have a manifest

### ISSUE THREAD

**Issue by djuarezg** [abrt/faf#917]
This is an issue when using upstream images from https://hub.docker.com/r/abrt/faf (and the same goes for faf-image)

These images do not have a manifest, therefore building or pulling can cause problems, such as:

```
# Simple pull, v1.13.1
[djuarezg@localhost container]$ docker pull abrt/faf:2.2.0
Trying to pull repository docker.io/abrt/faf ... 
manifest for docker.io/abrt/faf:2.2.0 not found
```

```
# Docker build
$ docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" -f container/Dockerfile_local .
Step 1/13 : FROM abrt/faf
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not ''
```

```
# Using Kaniko for building
error pushing image: failed to push to destination gitlab-registry.cern.ch/djuarezg/faf:master: MANIFEST_INVALID: manifest invalid; map[]
```

**Comment by ernestask** [comment]
Very likely because it was built with podman and has an OCI manifest (though not sure why Docker claims there’s nothing). I’ll see if I can rebuild and retag with the proper format.

**Comment by djuarezg** [comment]
FYI that is what I am doing: building them with podman (`make build_local`), retagging and pushing against our registry

**Comment by ernestask** [comment]
I’ve rebuilt the images on Docker Hub with Docker, so it should be fine now. I’ve also enabled automated builds a while ago, so any new releases should also behave identically.
