### ISSUE TITLE
cleanup-packages action does not completely delete packages from database 

### ISSUE THREAD

**Issue by djuarezg** [abrt/faf#926]
# Summary

On https://github.com/abrt/faf/blob/master/src/pyfaf/actions/cleanup_packages.py#L104-108 when cleaning up packages, even if lobs are deleted from storage, they are not deleted from the database (`packages` table). This means that a reposync will no longer download rpms.

# How to reproduce

```
faf releaseadd -o centos --opsys-release 7 --status ACTIVE
faf repoadd updates_debug dnf http://linuxsoft.cern.ch/cern/centos/7/updates/Debug/x86_64/ --nogpgcheck
faf repoassign updates_debug "CentOS 7" x86_64
faf pull-components
faf reposync --name-prefix glibc -d -v
```

After this we have packages on the database and lobs on storage.

```
faf cleanup-packages
```
After this we have packages on the database but no lobs on storage
Re-running `reposync` will state the following but no rpm is downloaded:
```
[2020-06-10 09:03:47] INFO:faf.RepoSync: Adding link between build glibc-debuginfo-common-2.17 operating system 'CentOS', release '7 and architecture x86_64
[2020-06-10 09:03:47] DEBUG:faf.RepoSync: Known package glibc-debuginfo-common-2.17-196.el7_4.2.x86_64.rpm
```
This means that once we cleanup packages we can no longer re-download them if needed, so retracing will not work anymore if trying to use the previously deleted packages.

Not sure if this is intended.

**Comment by djuarezg** [comment]
With my limited knowledge about the internals of this project, I think https://github.com/abrt/faf/issues/497#issuecomment-300392013 could help here as `reposync` in this case would need to check whether it actually need to redownload a package.

**Comment by ernestask** [comment]
I suppose the idea is that build removals from the database should cascade into the package table, because of the relationships. The issue you link to is somewhat related, but I’m not sure that would be a fix on its own (and even then it would be very time-consuming).

**Comment by ernestask** [comment]
Welp, shoulda read the code first, it does explicitly drop the packages.

**Comment by ernestask** [comment]
Right, so actually removing the packages from the database would have some consequences regarding reports, so it would be better to just re-download the missing LOBs for packages.
