### ISSUE TITLE
Development/Debug mode

### ISSUE THREAD

**Issue by buip** [abrt/faf#934]
Hi there,

I would love to contribute to faf. However, I don't know how to efficiently run faf in development/debug mode so that I can change and see the effects immediately. Could you let me know how you are currently doing it? Thank you!

**Comment by xsuchy** [comment]
It depends.

If you are running localy on bare metal, then you can just commit your change (no need to push) and run: `tito build --test --rpm -i`. This will build and install the package from latest commit.

If you use containers then see `make run_all_local` from https://github.com/abrt/faf/tree/master/container#how-to-build-the-image
