### ISSUE TITLE
Please help close this http://faf.lab.eng.brq.redhat.com/faf/reports/2915/

### ISSUE THREAD

**Issue by chuanchang** [abrt/faf#938]
It's a very old bug on RHEL-7.4 and missing original bug information in ftp://auto-hv-01.idmqe.lab.eng.bos.redhat.com/docker-runc-current.5895.1494660295.bkr-hv01-guest15.dsal.lab.eng.bos.redhat.com.tar.gz, please help close it to avoid to make noise for related mail listing, thanks!

**Comment by xsuchy** [comment]
I am afraid that we cannot provide any additional information and I have no idea how to resolve it. You have to reproduce it manually and then ask for the help developers of docker.
