### ISSUE TITLE
Unexpected System Error

### ISSUE THREAD

**Issue by tlastelick1** [abrt/faf#965]
I turned on and logged onto my computer today and received this message upon startup:
------------------------------------------------------------------------------------------------------------------------------------------

Unexpected system error
The system has encountered a problem and recovered.
Name kernel-core
Version 5.9.12-200.fc33.x86_64
First Detected 6 hours ago
Reported cannot be reported 
            ABRT Server
A kernel problem occurred, but your kernel has been tainted (flags:GOE). Explanation:
O - Out-of-tree module has been loaded.
E - Unsigned module has been loaded.
Kernel maintainers are unable to diagnose tainted reports. Tainted modules: 88x2bu.
------------------------------------------------------------------------------------------------------------------------------------------
I'm not sure what it all means (someone gained access to my computer?) and was hoping for an answer! 
Thank you!

**Comment by xsuchy** [comment]
It means that a software error happened in your kernel. This is likely error of developer. But your case cannot be reported because you use some 3rd party module that is unknown to us and likely to developers.
