### ISSUE TITLE
[qe-faf] Missing releases

### ISSUE THREAD

**Issue by msrb** [abrt/faf#990]
We received a report that there are some missing releases (rhel 8.4+8.5) in the QE FAF instance. I assume that this is a config issue on that particular instance (?) I.e. not an upstream FAF issue. But we should check.

**Comment by msrb** [comment]
Dropping the bug label as this might be just the configuration issue, not a bug.

**Comment by martinky82** [comment]
Indeed, that was an configration issue. I added the missing releases long ago and as of today, the release list on the production qe-faf is correct (incl. marking EOLed releases as such):

 http://10.0.204.193:8080/faf/summary/

**Comment by martinky82** [comment]
This issue can be closed.
