### ISSUE TITLE
Gateway timeout associating bug

### ISSUE THREAD

**Issue by opoplawski** [abrt/faf#995]
Trying to associate bug https://bugzilla.redhat.com/show_bug.cgi?id=2021090 with https://retrace.fedoraproject.org/faf/reports/277417 but I keep getting a 504 gateway timeout error.

**Comment by mgrabovsky** [comment]
Related note: We might not need write permissions, so the authentication might not be required – the _Get Bug_ method can be used without authn. However, authentication is required to read non-public bugs.

**Comment by mgrabovsky** [comment]
Related PR: #1016

**Comment by msrb** [comment]
Note this issue was reported long before Bugzilla changes the auth method, but symptoms do look the same.

**Comment by mgrabovsky** [comment]
This should be fixed now. I was able to associate [the report](https://retrace.fedoraproject.org/faf/reports/277417/) successfully.
