### ISSUE TITLE
Failed to fetch bug. Unable to save this bug due to unknown component 'kernel'

### ISSUE THREAD

**Issue by vbenes** [abrt/faf#997]
Cannot pair 
https://bugzilla.redhat.com/show_bug.cgi?id=2028102 

with 
https://faf.lab.eng.brq.redhat.com/faf/reports/23967/associate_bz

seeing
Failed to fetch bug. Unable to save this bug due to unknown component 'kernel'

**Comment by mgrabovsky** [comment]
Duplicate/related? #989

Regarding this specific report, I was able to associate the bug just fine:
![Screenshot from 2021-12-06 12-20-02](https://user-images.githubusercontent.com/134321/144837898-273ae275-a0c9-4034-b665-a6f213637b45.png)

**Comment by mgrabovsky** [comment]
This should be fixed by now.
